### PR TITLE
Add notes from September WG

### PR DESCRIPTION
**Pull request by benjie**

### CODE REVIEW

**Comment by glasser** [comment]
@benjie Will notes be posted for the October WG meetings? Or are the [live google docs notes](https://docs.google.com/document/d/1kXr_PgykVLMa5HKYdL73rOYSrO41dwJgh3H1pEQC3O0/edit) now the final place for minutes?

**Comment by benjie** [comment]
@glasser Anyone can submit a PR to add the notes to this repo, I tend to only upload the notes for meetings where I was one of the note takers (which has admittedly been most meetings over the last couple years, but not the last two). I recommend the "Docs to Markdown" GDocs addon for conversion, but you have to be careful the format in which you take the notes for it to work well.

**Comment by glasser** [comment]
Thanks, the doc didn't specify who was the notetaker so I assumed; wasn't sure if the process was just copying the live notes here or involved cleanup. (There's also something there about "<see meeting closed captions for the contents of this discussion>" which I don't know how to find.)

**Comment by benjie** [comment]
It's not possible to see them currently; hopefully when someone uploads the videos to YouTube we'll get the captions from that, but at the moment I don't have access to do so.

**Pull request merged**
