### PR TITLE
Add root operation types item to June agenda

### PR DESCRIPTION
**Pull request by benjaminjkraft**
Discussion in https://github.com/graphql/graphql-js/issues/3592

### CODE REVIEW

**Comment by benjie** [comment]
Sorry, CLAbot seems to have gone on holiday, let me poke someone...

**Comment by benjie** [comment]
I'm going to close and re-open this to see if that fixes it :man_shrugging:

**Comment by benjie** [comment]
@benjaminjkraft Please follow the CLA instructions above; let me know if you have any issues (or when it's done). Cheers!

**Comment by benjaminjkraft** [comment]
Sadly it looks like the CLA signing website is still not working -- I'm getting an infinite loading spinner and a 502 in the console when I try.  I'll try again tomorrow and see if it works better then!

**Comment by benjie** [comment]
If it fails again tomorrow, ping me and I'll chase up via the foundation.

**Comment by benjie** [comment]
@benjaminjkraft Any luck?

**Comment by benjaminjkraft** [comment]
Ok, it worked this time!

**Comment by benjie** [comment]
Welcome aboard!

**Pull request merged**
