### PR TITLE
Adjust time budgets for Jan 2022 WG

### PR DESCRIPTION
**Pull request by benjie**
We're massively over-subscribed for our 2 hours window; I've had to free up 40 minutes! To do so, I have made the following changes

1. Assumed that reviewing previous meetings action items should be limited to the single "ready to review" item
2. I've reduced the time allocated to @yaacovCR, @fotoetienne, @ilslv, @robrichard and myself
3. I've moved the shorter items to the front of the agenda

We're going to need to watch the clock and try and avoid going over the time budgets, we can always add more discussion to next months agenda or via PRs/issues/Discord.

@yaacovCR Since your change is two sentences I hope 10 minutes should cover it, and any ongoing discussion can take place on the PR.

@fotoetienne I'm sorry but I had to cut a full 10 minutes from your allocation, make sure you know what outcomes you want from your time and focus on reaching those :+1: 

@ilslv We don't have long enough for the kind of discussion we would normally have, I think you should quickly surface the inconsistency, and if a consensus is not reached rapidly you should collect interested parties (GitHub handles are in the agenda) and then open a discussion via a GitHub issues with those parties to discuss the direction.

@robrichard I had to cut 10 minutes from your allocation too, but since you're at the end if interested parties want to stay longer I guess they can :)

You are all welcome to reach out to me publicly or privately (e.g. via the GraphQL Discord) if you need any help/advice on what to do w.r.t taking discussions offline.

cc @leebyron

### CODE REVIEW

**Comment by benjie** [comment]
(I'd normally leave this open for review, but there's only a few hours before the WG so I've merged it early.)

**Comment by ilslv** [comment]
@benjie I'm glad to see so many people interested in WG! Considering all this I think I should drop out of today's conversation entirely, and instead describe all possibilities and caveats in a GutHub issue first. Especially considering that it involves concrete spec wording, which is better perceived in written form.
In case GitHub issue goes nowhere, I'll re-apply to the next WG.

**Comment by benjie** [comment]
That sounds great; we look forward to welcoming you to the February working group :raised_hands: I've raised https://github.com/graphql/graphql-wg/pull/847 for this; I think you're saying to remove you from the attendees too so I will do that, but if I'm mistaken please do attend anyway if you want and we can correct it in a follow-up PR.

I've spread your time across @robrichard and @fotoetienne :raised_hands:

**Comment by mjmahone** [comment]
@benjie for the fragment modularity agenda item: we *should not* get into an in depth discussion here, unless we have time at the end of the meeting. I explicitly only gave 5 minutes so that all I have time to do is make a call for contributors, as we're probably going to want to have a dedicated, well-scoped group working through this space (similar to what @twof has done with Client Controlled Nullability, where we work through problems then give WG updates). So *this meeting* the discussion should basically just be "contact me if you want to be part of a 1-2 hour deeper discussion in the next week or so".

I'll do my best to keep us focused and I'll keep a timer going to cut us short if we start going off that thread :)

**Comment by leebyron** [comment]
Very exciting to see a packed agenda, we'll get through as much as we're able. Thank you @benjie for keeping us on track

**Pull request merged**
