### PR TITLE
Add minutes from Jan, Feb, and Mar 2020 meetings

### PR DESCRIPTION
**Pull request by brianwarner**
I've converted the meeting minutes from Google Docs to markdown.

For what it's worth, I'm using the "Docs to Markdown" Gsuite app, and getting accurate results.

Signed-off-by: Brian Warner <brian@bdwarner.com>

### CODE REVIEW

**Comment by benjie** [comment]
Nice, good job @brianwarner. Is there any changes we should adopt into note taking to improve the markdown output? I already try and use the header 1/2 presets rather than manual formatting, but I’m wondering if we can do something to make the action highlights come through? Perhaps just bold them in future?

**Comment by benjie** [comment]
Please can someone merge this? @IvanGoncharov  @leebyron

**Comment by leebyron** [comment]
Amazing, thanks again!

**Comment by brianwarner** [comment]
@benjie What you did was great.  Please feel free to keep using the headers, the conversion script picks them up and Does The Right Thing.

As for the action highlights, I might suggest accumulating them in a list at the top of the minutes, or at the end.  To answer the other part of your question, the formatting itself doesn't really matter so long as it's something which translates to markdown (e.g., bold and italic are fine, but text coloring or highlights might not work).

@leebyron You're welcome!  I'll keep an eye on these for you from now on.

**Comment by benjie** [comment]
Thanks @brianwarner :+1:

**Pull request merged**
