### PR TITLE
Add Greg Wardwell to attendees

### PR DESCRIPTION
**Pull request by gwardwell**

### CODE REVIEW

**Comment by michaelstaib** [comment]
Hey @gwardwell can you sign the CLA?

**Comment by gwardwell** [comment]
@michaelstaib sorry it took me a while, I needed to clear signing the agreement as individual versus corporate with my company. I just signed.

**Comment by benjie** [comment]
Hey Greg; great news! There's a meeting in a few hours - do you want to add yourself to that meeting instead? https://github.com/graphql/graphql-wg/edit/main/agendas/2022/12-Dec/wg-secondary-eu.md

**Comment by benjie** [comment]
Hi @gwardwell I'm going to close this PR since you didn't attend that meeting (did you?), but please feel free to add yourself to a future meeting :)

**Pull request closed without merging**
