### PR TITLE
Add Young Min Kim to the May WG

### PR DESCRIPTION
**Pull request by aprilrd**

### CODE REVIEW

**Comment by aprilrd** [comment]
I am waiting for Netflix corporate CLA, which is set up by @fotoetienne

**Comment by benjie** [comment]
@aprilrd Looks like you also need to edit your git history so the commit is correctly attributed to you.

**Comment by aprilrd** [comment]
Oops my bad, @benjie fixed!

**Comment by benjie** [comment]
Nice; once Netflix have done the required setup you should be able to click the “please click here” link above to be approved 👍

**Pull request merged**
