### PR TITLE
Add PowerPoint link for a Dec agenda item

### PR DESCRIPTION
**Pull request by aleksandarsusnjar**

### CODE REVIEW

**Review by benjie — COMMENTED** [review]
You can present this during the meeting using screen sharing, but it would be helpful if you shared a more universal file type such as PDF or a web-hosted variant such as Google Slides.

**Comment by aleksandarsusnjar** [comment]
@benjie This is a presentation form of the other, more detailed, Markdown document. It exists separately as it can use animations not available to PDFs ... and I am more proficient with PowerPoint than with Google Slides. I am not 100% sure this needs to be shared as such (Markdown doc should be enough) but I'll let you guys decide.

**Review by benjie — APPROVED** [review]

**Comment by mjmahone** [comment]
Even with the powerpoint, I would still *highly* recommend making a PR in the WG under https://github.com/graphql/graphql-wg/tree/main/rfcs. Reading through the powerpoint, there's a lot of prior art this is similar to past proposals. People often read through the agenda before the WG meeting, and leave comments ahead of time to help clarify the discussion.

PRs to the WG can be labelled as "Strawman" i.e. you're just bouncing ideas and seeing if there's something deeper as a community we should look into.

**Comment by aleksandarsusnjar** [comment]
@mjmahone I could certainly do that. I am just not familiar with the expected process, yet. Yes, I am, at this time, just bouncing ideas, am aware that there is prior art and attempted to list some but I may have missed additional sources.

The PowerPoint isn't meant to stand on its own. Markdown document I linked can. Do you mean that I should create a PR to add it to the RFCs?

**Pull request merged**
