### PR TITLE
Adding myself for December meeting.

### PR DESCRIPTION
**Pull request by Adron**

### CODE REVIEW

**Comment by benjie** [comment]
@Adron If you've resolved the CLA, please click the link above and the status should update :+1:

**Comment by Adron** [comment]
Hey @benjie I just clicked the "Please click here to be authorized" and it still just send me to the loop to send a request again.  🤷🏼‍♂️

**Comment by benjie** [comment]
@brianwarner Are you able to give any pointers?

**Comment by brianwarner** [comment]
Hi @Adron, I was talking with Rob, and it seems like you'll need to request that he add you using his Gmail address. Once he adds your username, you'll have to click through the link one more time to confirm you actually want to be covered by AWS.

**Comment by Adron** [comment]
Oh ok, will send @robzhu @ that addy and follow up here, thanks @brianwarner.

**Comment by Adron** [comment]
Got it sorted! CLA signed 👍🏻

**Comment by benjie** [comment]
@Adron Are you able to resolve the conflicts? For some reason the web resolver doesn't seem to be available :man_shrugging:

**Comment by Adron** [comment]
Hey @benjie yeah, it cleared above. Should show all green and approved. I believe someone with permission should just be able to merge it now.

**Comment by benjie** [comment]
I meant the git conflicts; but I've done it on the command line :+1: 

Where did the GitHub conflict resolver go :disappointed:

**Pull request closed without merging**
