### PR TITLE
Add self to attendees

### PR DESCRIPTION
**Pull request by mjmahone**
Will be attending in-person.

### CODE REVIEW

**Comment by hwillson** [comment]
@mjmahone @leebyron Out of curiosity, do you have a physical location for the meeting set? We'd be happy to host the meeting at Apollo HQ if you don't yet.

cc @martijnwalraven @jbaxleyiii

**Comment by leebyron** [comment]
I don't have a physical location - I'll personally not be able to make it to a physical meetup, but I think having space for one for those who can make it would be valuable!

**Comment by IvanGoncharov** [comment]
> We'd be happy to host the meeting at Apollo HQ if you don't yet.

@hwillson It would be great 👍I will definetly join you for the call.
You can add location to the agenda similar to what we had for GraphQL Europe:
https://github.com/graphql/graphql-wg/blob/master/agendas/2018-06-14.md#physical-locations

**Comment by abernix** [comment]
@IvanGoncharov 	@hwillson 	@leebyron 	I've opened a PR which suggests Apollo HQ for the physical location: https://github.com/graphql/graphql-wg/pull/121 We're happy to host all attendees!

**Pull request merged**
