### PR TITLE
Add myself into the meeting + Agenda :)

### PR DESCRIPTION
**Pull request by syrusakbary**
Add myself into the meeting + Agenda :)

### CODE REVIEW

**Comment by leebyron** [comment]
Hey @syrusakbary - I'd like to keep the agenda fixed, could this discussion on optionality be part of your agenda item? Also, it would be great if you could link to the proposal or other context for your agenda item so others can prepare

**Comment by syrusakbary** [comment]
Sure! Let me work on the proposal/context for the item.
Will ping you here once is ready to re-review

**Comment by leebyron** [comment]
Sorry to have missed you this time, @syrusakbary

**Comment by syrusakbary** [comment]
Will be in the next one! :)

**Pull request closed without merging**
