### PR TITLE
Update 2021-05-06.md

### PR DESCRIPTION
**Pull request by twof**

### CODE REVIEW

**Comment by leebyron** [comment]
Thanks @twof - happy to have you join. Would you mind signing the CLA?

**Comment by twof** [comment]
@leebyron Yep! Talking with legal at Yelp about how to get a corporate signature. I'll make sure it gets done before the meeting.

**Comment by twof** [comment]
@leebyron I think we should be good to go for me. I'm working on getting one of my coworkers also set up to sign our corporate CLA. Let me know if I need to do anything else to get approved!

**Comment by benjie** [comment]
@brianwarner CLA issues; can you help?

**Comment by benjie** [comment]
@twof from Brian's comment [here](https://github.com/graphql/graphql-wg/pull/674#issuecomment-831961838) I think you might need to click the "Please click here to be authorized" button again and follow the flow to prove you're part of Yelp's GitHub Organization. Once done, please ping me again :+1:

**Comment by twof** [comment]
When I click "Please click here to be authorized" I get `{"message": "Internal server error"}`. Maybe this is a bug with the system? I'm signed on as the CLA manager for my company I think.

**Comment by twof** [comment]
@benjie (forgot to tag you)

**Comment by brianwarner** [comment]
Yes, we're having an SSO outage at the moment, unfortunately.

**Comment by twof** [comment]
@brianwarner Thanks for the heads up! I'll check back again later today.

**Comment by twof** [comment]
@benjie Looks like we're good to go!

Thanks for your help @brianwarner

**Comment by benjie** [comment]
Great 👍 I’m afraid your PR has brought back some things that were removed; would you mind editing them back out again please?

**Comment by twof** [comment]
@benjie ope looks like it was a bad merge on my part. I think I've fixed it.

**Review by benjie — APPROVED** [review]

**Pull request merged**
