### PR TITLE
Add Cory Monty to 2019-06-06 + Dynamic variable declaration

### PR DESCRIPTION
**Pull request by cmonty**
Related to https://github.com/graphql/graphql-spec/issues/377

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@cmonty I checked graphql/graphql-spec#377 and don't see anything about "Pipeline Mutations" can you please submit issue or PR to https://github.com/graphql/graphql-spec with some details so other participants can prepare.

**Comment by cmonty** [comment]
@IvanGoncharov sorry about that! I have updated the agenda item and description as we want to talk about the `@export` directive in the context of nested mutations within a single query. @lkorth may end up opening a new issue, in which case I'll update the agenda.

**Comment by IvanGoncharov** [comment]
@cmonty Thanks for clarification.

**Comment by cmonty** [comment]
@leebyron Absolutely! I'll add some links.

**Comment by cmonty** [comment]
Now relates to https://github.com/graphql/graphql-spec/issues/583 and added link to the agenda

**Comment by cmonty** [comment]
Going to skip this topic, tomorrow.

**Pull request merged**
