### PR TITLE
Add Martijn Walraven to December 7th WG meeting

### PR DESCRIPTION
**Pull request by martijnwalraven**

### CODE REVIEW

**Comment by hwillson** [comment]
@martijnwalraven you're covered under our CLA (and in the system) so the failure above leads me to believe you're coming across as an individual instead of part of an organization. You might need to open a new PR and be sure to select organization for the CLA part.

**Comment by hwillson** [comment]
@martijnwalraven or you could try clicking on the `Details` link for the EasyCLA check and see if you can authorize things that way.

**Comment by benjie** [comment]
If memory serves, this can be caused by the email address associated with your git commits. That's just one possibility though. Feel free to experiment [over here](https://github.com/graphql/easycla#graphql-specification-membership-onboarding) as that repo is intended for testing of the EasyCLA integration.

**Comment by benjie** [comment]
I'm going to merge anyway, but please do try and get EasyCLA passing for you :+1:

**Pull request merged**
