### PR TITLE
Added Alessia Bellisario to September wg Meeting

### PR DESCRIPTION
**Pull request by alessbell**

### CODE REVIEW

**Comment by benjie** [comment]
Hi @alessbell you should be covered by Apollo's CLA; please reach out internally to the relevant party to add you to the relevant list (sorry, I'm not sure who that is - perhaps @hwillson?) and then click the link above. Thanks!

**Comment by hwillson** [comment]
It is me - thanks for the ping @benjie! @alessbell adding you momentarily.

**Comment by hwillson** [comment]
@alessbell you should be good to go now!

**Comment by alessbell** [comment]
Thanks @hwillson!

**Pull request merged**
