### PR TITLE
Update CompositeSchemas.md

### PR DESCRIPTION
**Pull request by ralfhandl**

### CODE REVIEW

**Comment by benjie** [comment]
Hi @ralfhandl are you able to sign the CLA?

**Comment by ralfhandl** [comment]
Hi @benjie, I definitely want to get it signed, and am working on finding out who in my company is entitled to do that.

**Comment by ralfhandl** [comment]
@leebyron I got the approval process started and hope to participate in the next workgroup meeting.

**Comment by benjie** [comment]
@ralfhandl Bump :wink:

**Pull request closed without merging**
